#!/bin/sh

handler="`pwd`/handler.sh"
monitorDirectory="`pwd`/watchme"
altMonitorDirectory="`pwd`/watchme2"

echo "Monitoring: $monitorDirectory and $altMonitorDirectory"
echo "Handler: $handler"

docker run --rm --name monitor \
  -v "$monitorDirectory" \
  -v "$handler" \
  -v "$altMonitorDirectory" \
  -e "MONITOR1=$monitorDirectory" \
  -e "MONITOR1_HANDLER=$handler" \
  -e "MONITOR2=$altMonitorDirectory" \
  -e "MONITOR2_HANDLER=$handler" \
  ecor/watchfs
